spring:
  application:
    #指定微服务名称
    name: eureka-client


  cloud:
    consul:
      host: localhost
      port: 8500


server:
  port:  2222

eureka:
  client:
    serviceUrl:
      #  指定服务注册中心的位置
      defaultZone:  http://localhost:1111/eureka/
