spring:
  application:
    #指定微服务名称
    name: eureka-client


server:
  port:  2222

eureka:
  client:
    serviceUrl:
      #  指定服务注册中心的位置
#      defaultZone:  http://localhost:1111/eureka/
       defaultZone:  http://peer1:1111/eureka/,http://peer2:1112/eureka/